# Generated by Django 5.2.7 on 2026-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
