# Generated by Django 5.2.7 on 2026-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_model_alter_asset_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
