# Generated by Django 5.2.7 on 2026-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asset_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
