# Generated by Django 5.2.7 on 2026-04-09 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_request_remarks_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_borrowed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='item_count',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
