# Generated by Django 4.2.30 on 2026-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_request_date_borrowed_request_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
